### ISSUE TITLE
Name of the ZFS pool - installer limitation (hard-coded `zroot`)

### ISSUE THREAD

**Issue by z11k** [yaroslav-gwit/HosterCore#89]
hi,

i found this project interesting.

to this part mentioned on https://docs.hoster-core.gateway-it.com howto:

* OS/root ZFS pool name must be kept as zroot

we have various pool and we know why they was named like that and not interested in having the same like other, so feature request: can it be the name of pool matter of choice?

thx

**Comment by yaroslav-gwit** [comment]
Hey. Thanks for you comment.

`zroot` was hard-coded in a couple of places since the beginning of the project (when it was still hard to predict where we are going, what would be the real-world usecase, etc), and it will take some effort to completely get rid of it. With that said, `Hoster` fully supports multiple datasets apart from `zroot`.

So as long as `zroot` is present on the system you can keep your VMs anywhere you want. Just add them into the `host_config.json` as:
```json
    "active_datasets": [
        "zroot/vm-encrypted",
        "zroot/vm-unencrypted",
        "your-pool-name-here/your-custom-dataset",
        "your-pool-name-here/another-custom-dataset"
    ]
```

And just an FYI, the `release` version is very old at this point, so if you want to try out `Hoster` please follow the instructions in the docs to install the `dev` version. Or wait a couple of days before installing it - I am aiming to release a new version tomorrow at some point (if everything goes well).

**Comment by yaroslav-gwit** [comment]
I have opened a separate issue that will help with your problem: https://github.com/yaroslav-gwit/HosterCore/issues/92
If you don't have any more questions/requests, then I'll be closing this shortly.

**Comment by z11k** [comment]
> `zroot` was hard-coded in a couple of places since the beginning of the project (when it was still hard to predict where we are going, what would be the real-world usecase, etc), and it will take some effort to completely get rid of it.

hi, thanks for answer. I was afraid reason like that and it is not only because nobody asked before. I have not much good experience with same or generic pool name series. so i know and  now i can give it test. Thank you

**Comment by yaroslav-gwit** [comment]
Feel free to open a new issue, if you have more questions, but I am now closing this one.
